### ISSUE TITLE
any instructions on how to install on a mac?

### ISSUE THREAD

**Issue by rgupta1234** [zalando-incubator/kopf#101]
## Expected Behavior
kopf binary installs

## Actual Behavior
sh-3.2# pip install kopf
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: kopf in /Library/Python/2.7/site-packages (0.0)
sh-3.2# kopf
sh: kopf: command not found
sh-3.2# 

sh-3.2# find . -name kopf
./Library/Python/2.7/site-packages/kopf
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Platform: Mac
  - Kubernetes version: *(use `kubectl version`)*
h-3.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}

  - Python version: Python 2.7.10
  - Python packages installed: *(use `pip freeze --all`)*

sh-3.2# pip freeze --all
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
altgraph==0.10.2
ansible==2.4.2.0
asn1crypto==0.24.0
bcrypt==3.1.4
bdist-mpkg==0.5.0
bonjour-py==0.3
boto==2.48.0
boto3==1.5.2
botocore==1.8.16
cffi==1.11.2
cryptography==2.1.4
Django==1.11.20
docutils==0.14
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.19
Jinja2==2.10
jmespath==0.9.3
kopf==0.0
macholib==1.5.1
MarkupSafe==1.0
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
paramiko==2.4.0
pip==19.1.1
py2app==0.7.3
pyasn1==0.4.2
pycparser==2.18
PyNaCl==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==2.6.1
pytz==2013.7
PyYAML==3.12
s3transfer==0.1.12
scipy==0.13.0b1
setuptools==18.5
six==1.11.0
vboxapi==1.0
xattr==0.6.4
zope.interface==4.1.1
```
```

**Comment by nolar** [comment]
@rgupta1234 Kopf works on Mac normally (I personally develop it on Mac).

Kopf requires Python >= 3.7 — as specified in setup.py. It will not work with 2.7, as there are no required libraries & syntax constructs (e.g. async/await).

Please, use any Python 3.7+ installation of Python — e.g. via [pyenv](https://github.com/pyenv/pyenv), or [brew](https://brew.sh/)'s [python3](https://formulae.brew.sh/formula/python#default).

I'm not sure which Python version is used in Mac OS by default, as I never used it for development, as it is a bad idea to install anything into the system Python (it can break the system).
