### ISSUE TITLE
Embedded Example Broken

### ISSUE THREAD

**Issue by cliffburdick** [zalando-incubator/kopf#184]
## Expected Behavior
Example working

## Actual Behavior
Wrong syntax

## Steps to Reproduce the Problem

1. Run the embedded example here:
https://kopf.readthedocs.io/en/latest/embedding/

2. You will see ```TypeError: __init__() got an unexpected keyword argument 'target_fn'``` since the actual parameter is "target".

3. Once that's fixed, if you make ```def main``` into ```if __name__ == '__main__'```, you will see this:

```
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 11, in kopf_thread
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

4. After trying to hack around that by adding ```asyncio.set_event_loop(asyncio.new_event_loop())``` before the loop assignment, I get:
```AttributeError: module 'kopf' has no attribute 'operator'```

## Specifications

  - Platform: Ubuntu 18.04
  - Kubernetes version: None
  - Python version: 3.7.4

Also, is it possible to not require python 3.7?

**Comment by nolar** [comment]
@cliffburdick Regarding Python>=3.7 requirement: Kopf will not function with 3.6 anyway, as it uses some 3.7+ features and modules actively in its core (e.g. `contextvars`, but there are others). See #74 on reasoning.

**Comment by nolar** [comment]
@cliffburdick The `target=` is fixed now in the docs. And a real runnable example is added. So, I assume, this issue is done. If not, feel free to re-open.
