### ISSUE TITLE
Error in kopf/updates.rst

### ISSUE THREAD

**Issue by chungktran** [zalando-incubator/kopf#238]
## Expected Behavior
Returns the current `spec.size`

## Actual Behavior
Returns `None`

## Steps to Reproduce the Problem
https://github.com/zalando-incubator/kopf/blob/master/docs/walkthrough/updates.rst
  1. The line `size = spec.get('create_fn', {}).get('size', None)` in `kopf/updates.rst` does not return a valid size. It returns `None` because there's no `create_fn` key in `spec`. It should be the size of the current `spec.size`
  1. Doing `logger.info(f'%s', spec)` shows that it only has the `size` key, no such `create_fn` key

**Comment by nolar** [comment]
This should be `status`, not `spec`. I'll fix it. Thanks for noticing.

**Comment by nolar** [comment]
Fixed in #97.
