### ISSUE TITLE
Question: How to monitor child resources and change CRD state accordingly?

### ISSUE THREAD

**Issue by jmdacruz** [zalando-incubator/kopf#268]
I'm probably missing something obvious. For instance, say I have an operator that reacts to the creation of a `CRD` by creating a `Deployment` that has a `ReplicaSet` with `N` pods, I'd like to reflect on the `CRD`'s status the fact that the sub-resources have been created correctly, or else set the status of the `CRD` to an error. What's the proper pattern for this?

(I'm giving it a try at building a Celery operator: https://github.com/jmdacruz/celery-k8s-operator)

**Comment by sebgoa** [comment]
https://www.youtube.com/watch?v=rN_rQU92T5s See at 14:36

**Comment by jmdacruz** [comment]
Awesome! That video is pretty cool, thanks for sharing!
