### ISSUE TITLE
Cannot see print statements in container log

### ISSUE THREAD

**Issue by jicowan** [zalando-incubator/kopf#291]
## Question

I cannot see my print() statements in the container log for my operator.  Here is an example: 
```
def check_list_size(selectors):
    if len(selectors) > 5:
        print("Exceeded maximum selectors. You may only have up to 5 selectors in a Fargate profile.")
    else:
```

I've also tried using the python logging library.  That didn't work either.  All I see are the event/logs from the operator framework. 

## Checklist

- [ x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [ x] I have searched in the [GitHub Issues](https://github.com/zalando-incubator/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

logs print logging

**Comment by jicowan** [comment]
I am also having an issue with try except statements.  It doesn't appear that kopf is honoring them.  It is also failing to detect the region.  I created another operator with an earlier version of kopf and didn't have this issues.

**Comment by nolar** [comment]
Hm. I'm not sure how I can help here. Kopf does not intercept stdout/stderr, so all the prints should be visible — especially if regular log messages are visible.

Can you please share a code snippet to reproduce the issue? And the way how you start the operator: is it `kopf run` CLI command, or is it your own process?

Also try putting `print()` outside of any ifs — maybe the condition if not met or the function is not called at all?

**Comment by jicowan** [comment]
Thanks @nolar. There was an exception before my print statement ran.  Sorry for the confusion.  I should have caught that before opening an issue.
