### ISSUE TITLE
Creating a DAG operator

### ISSUE THREAD

**Issue by seperman** [zalando-incubator/kopf#299]
## Question

How would you go about creating a dynamic DAG (Directed acyclic graph) operator using Kopf?

## Checklist
For example [Argo](https://github.com/argoproj/argo) uses operators to create DAGs in Kubernetes.

What I'm thinking about is:

- Having an in memory mutable version of the dag in the operator. Every time that the dag gets modified or a node in the dag is traversed (a pod finished execution), the state of the dag gets dumped to Kubernetes etcd via a configmap. This is done for persistence in case the operator restarts.

Any help is appreciated.
Thanks.

## Keywords

Priority Queue, DAG

**Comment by nolar** [comment]
Sorry for the late response. I cannot help here much, as I am not familiar with your domain. But your way of solving it seems sufficient and normal — should work. Are there any specific problems why this does not work?

**Comment by seperman** [comment]
Hi,
Thanks for responding. I decided to use RDBS instead of dumping the state to k8.
Sep
