### ISSUE TITLE
Censor Authorization header in "Failed to post an event" logs

### ISSUE THREAD

**Issue by thilp** [zalando-incubator/kopf#305]
First, thank you so much for Kopf! After working on Kubernetes operators in Go, it's so refreshing!

## Problem

When Kopf fails to post an event, it logs the whole HTTP request, including the Authorization header. This exposes the OAuth token used by the operator to anyone who can access these logs.

For example:
```
kopf.clients.events  [WARNING ] Failed to post an event. Ignoring and continuing. Error: ClientResponseError(RequestInfo(url=URL('https://10.3.0.1:443/api/v1/namespaces/my-crd/events'), method='POST', headers=\u003cCIMultiDictProxy('Host': '10.3.0.1', 'Authorization': 'Bearer +++JWT_TOKEN_REDACTED+++', 'User-Agent': 'kopf/unknown', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '1078')\u003e, real_url=URL('https://10.3.0.1:443/api/v1/namespaces/my-crd/events')), (), status=500, message='Internal Server Error', headers=\u003cCIMultiDictProxy('Content-Type': 'application/json', 'Date': 'Mon, 03 Feb 2020 09:47:36 GMT', 'Content-Length': '246')\u003e). Event: type='Error', reason='Logging', message='exception: …'.","stream":"stderr","time":"2020-02-03T09:47:36.828556769Z"}
```
(Notice the `Bearer +++JWT_TOKEN_REDACTED+++` part.) The exception is a custom exception legitimately raised in a handler. My understanding is that Kopf is behaving properly here, he's just being a bit too verbose in his error reporting and shares the operator's token with everyone.

I imagine that telling Kopf to log only errors (not warnings) would solve the problem, but I'm interested in these kind of events happening in production.

## Proposal

I would like to keep a similar level of logging (e.g. I'm interested that these events could not be posted) but, at least in production, I would like the `Authorization` header to be removed or (better) censored, so that I don't get vulnerability alerts from my company's security team. :wink: Writing code with Kopf is so (nicely) high-level that I no longer have to take care of implementation details like cluster authentication, so even if the `Authorization` header was censored in all cases (i.e. no distinction between dev and prod environments) I would not care, because I have trouble imagining a case where I would need to troubleshoot something using this header.

I would recommend having this `Authorization` censoring on by default, and perhaps if it's really a problem you could disable it with [EventsConfig](https://kopf.readthedocs.io/en/latest/packages/kopf.config/#kopf.config.EventsConfig):

```python
import kopf.config

kopf.config.EventsConfig.hide_authorization_header = False
```

## Checklist

- [ ] Many users can benefit from this feature, it is not a one-time case
- [ ] The proposal is related to the K8s operator framework, not to the K8s client libraries

**Comment by nolar** [comment]
What about censoring the whole `aiohttp.ClientResponseError`'s repr, and only showing the HTTP status and message? Who knows what other sensitive headers it can leak by dumping the original request.

See #306 for a draft solution.

**Comment by thilp** [comment]
That would also work for me, and it's indeed probably safer. Thank you for the fast answer!
