### ISSUE TITLE
Patch verb needed on read only watches

### ISSUE THREAD

**Issue by klenje** [zalando-incubator/kopf#318]
## Long story short
Read operations are requiring Patch verb, while I would expect that only get/list/watch operations are needed. Any reason behind this?

## Description

<details><summary>The code snippet to reproduce the issue</summary>

```python
import kopf
import logging
import asyncio

@kopf.on.update('', 'v1', 'nodes', labels={'test': 'true'})
async def node_in_sight(name, meta, **kwargs):
    logging.info("Caught {}!".format(name))
```

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: clusterrole-test
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [list, get, watch]
```
</details>

<details><summary>The full output of the command that failed</summary>

```
 File "/usr/local/lib/python3.7/site-packages/kopf/clients/patching.py", line 54, in patch_obj
    raise_for_status=True,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 588, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://172.30.0.1:443/api/v1/nodes/localhost')
```
</details>

It works fine when adding patch verb on nodes as below
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: clusterrole-node-recreator
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [list, get, watch]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [patch]
```

## Environment

* Kopf version: 0.25
* Kubernetes version: 1.11
* Python version: 3.7

</details>

**Comment by pshchelo** [comment]
@klenje kopf stores the last handled state of the resource in a custom annotation of that very resource, this is how it detects what has changed.
Thus, after the resource handler finishes, kopf has to update the annotation on the resource with the last state it has acted on - thus a need for patch verb to be allowed.

**Comment by pshchelo** [comment]
While this quite simplifies the code (there's no need to run a separate 'state' storage) it has some drawbacks.
Just to share our on pains:
we need to watch .status of Deployments. The thing is - deployment's generation is a) present in status and b) is bumped on annotation changes too! (presumably as K8s stores its own data for rollback there and thus aggros on every change to annotations, bug?). Which creates a self-feeding loop - kopf sees status change -> kopf handles status change -> kopf patches annotation -> k8s bumps generation in status -> kopf sees status change...
We had to resort to only watching .status.conditions and have some heuristic logic to derive the actual status afterwards. It still results in multiple back-and-forth between k8s and kopf and Deployment's generation is bumped several times, but at least no infinite loop is created that way.

**Comment by klenje** [comment]
Thanks for the explanation and the insights! Indeed the impact of the choice needs to be considered based on the resource you want to watch, no such loops in my case.
