### ISSUE TITLE
[proposal] Inject predefined k8s api client into handlers

### ISSUE THREAD

**Issue by eshepelyuk** [zalando-incubator/kopf#366]
## Problem

It's frequent case when handlers need to interact with k8s API.
Currently there's a need to write boilerplate code for this, initializing k8s api client manually in operator code. 

## Proposal

`kopf` could inject either `pykube-ng` or native `kubernetes` client into handler, based on some sane defaults, e.g. - use config from service account.

Injecting `pykube-ng` based client

```python
import kopf
import pykube


@kopf.on.create('', 'v1', 'services')
async def handle_service(name, pykube_client, logger, **_):
    pods = pykube_client.Pod.objects(api).filter(namespace=pykube.all)    
    logger.info(f"created service {name}, num: {len(pods)}")
```

Injecting `kubernetes` based client

```python
import kopf


@kopf.on.create('', 'v1', 'services')
async def handle_service(name, k8s_client, logger, **_):
    pods = k8s_client.list_pod_for_all_namespaces(watch=False)
    logger.info(f"created service {name}, num: {len(pods)}")
```

## Checklist

- [x] Many users can benefit from this feature, it is not a one-time case
- [x] The proposal is related to the K8s operator framework, not to the K8s client libraries

**Comment by nolar** [comment]
Thank you for your suggestion.

Can you please clarify what would be a benefit over initialising those clients in place, either as module-level vars or in each handler/on each use? E.g.:

```python
api = pykube.HTTPClient(pykube.KubeConfig.from_env())
```

(`from_env()` is an equivalent of in-cluster first, from kube-config second.)

**Comment by eshepelyuk** [comment]
The benefits 

1. less boilerplate code, users of `kopf` will not care about creating a client themselves
1. speed of code execution, i.e. client doesn't need to be created on each handler
1. reusal of a already existing component ( i belive kopf has own client inside)

**Comment by nolar** [comment]
Kopf directly uses `aiohttp` inside (historically, started with `kubernetes`, then switched to `pykube-ng`, then to `aiohttp`) — and it is completely hidden from the users, so that it can be changed in the future.

`pykube-ng` and `kubernetes` libraries are only used to extract authentication information from them, if installed ([piggybacking](https://kopf.readthedocs.io/en/latest/authentication/#piggybacking)). No client capabilities are used, and no config/client/session objects are used internally.

Yet here I agree, that manipulating K8s objects is the most common task for operators. It is worth finding a way to make it easier without turning Kopf into a client with its own K8s DSL. 

I now think of a plugin-like system, which will be able to inject their own kwargs from 3rd-party libraries by only installing them — and so, all K8s clients could be made supportable, not only these two. Basically, the same result can be achieved by explicit decorators with no involvement of Kopf. I'll think about this.

**Comment by eshepelyuk** [comment]
What about introducing new decorator annotation that could return customized kwargs that can be injected in various handlers ?

**Comment by eshepelyuk** [comment]
@nolar while implementing a sort of "plugins" for injecting k8s clients can be a long process - there can be an improvement to docs that can handle many cases and prevent error working with kopf.

Im talking about providing some good examples of using synchronous k8s client inside _asynchronous_ kopf handlers.
Currently there's only examples of k8s client from _synchronous_ handlers. 

I understand that this request may sound too straightforward and obvious for experienced Python developer, but for many adopters like me, who do program some Python but are not senior Python developers, such examples would be a really great tool for quicker kopf adoption.

**Comment by nolar** [comment]
@eshepelyuk Can I ask, why do you want to use sync clients in async functions? What is the use-case?

Async functions should only use async I/O (read as: async API clients in case of K8s operators). A synchronous call blocks the whole asyncio event loop, so no single coroutine or i/o happens in that event loop. This could lead to either delayed reactions and throttling in the best case, or to connection timeouts in other cases — in the whole operator, not only for one resource.

This topic is not Kopf-specific, it is related to general asynchronous programming. This might be a good article to read about it: https://www.aeracode.org/2018/02/19/python-async-simplified/ — especially the "Sync From Async" section.

This is also a reason why all Kopf examples use sync-handlers with `def`, not `async def` — for simplicity.

I've made a little page on this topic — https://kopf.readthedocs.io/en/latest/async/ — but I prefer not to turn Kopf's docs into generic Python tutorial. I would be happy to add a couple of links to good articles explaining async programming in Python there, but I have troubles finding them (mostly, identifying them as "good enough" for different levels). If you have some — please suggest.

**Comment by eshepelyuk** [comment]
@nolar i'm really open to provide some clues, that are quite obvious for me but maybe missing some background for others

1. There's no need to copy asyncio into `kopf` docs, cause my _only request_ was to describe in `kopf` a _single_ common case for an operator - _interact with K8S API_, ie what most of the operators are usually created for. Personally i already had quite enough understanding of asyncio to be able to choose that i really want to leverage asyncio on my python code, in my kopf based operator. 
And apparently I;m not going to use sync code in async handler direclty ! My request implied that I asked about exact examples how to wrap sync calls with asyncio to use them properly in async handlers of `kopf`
1. My motivation while creating `kopf` operators that I want those processes (containers) to be as lightweight as possible - i.e. do not want to spawn unnecesary threads for sync handlers and daemons, do not waste CPU for thread context swithching, avoid python single thread lock and do not fall into a problem when there's  a limitation on number of threads (this problem was already raised here in issues)
1. So, with the motivation explained above - the model I find the most lightweight and performant is to reuse asyncio because
** `kopf` already uses asyncio under the hood, for handlers daemons etc
** for my custom purposes, i believe that creating and running a new single dedicated proactor event loop and use it for executing my own asyncio calls will be much performant then spawning threads and wasting CPU for context swtiching.

**Comment by nolar** [comment]
@eshepelyuk Interaction with K8s API is described in the tutorial section of Kopf's docs; synchronous though: https://kopf.readthedocs.io/en/latest/walkthrough/creation/#creation

Or it should be a separate example with another async client called from an async handler. Or the existing sync client wrapped into asyncio ThreadPoolExecutor in an async handler (but why?).

Or I probably do not fully understand what you propose. I would appreciate if you describe it as a code snippet here — for clarity.

**Comment by eshepelyuk** [comment]
@nolar nevermind, closing the issue
thanks for time spent on it.
