### ISSUE TITLE
Is there any real world use of kopf,like rook/ceph?

### ISSUE THREAD

**Issue by tarjintor** [zalando-incubator/kopf#380]
Hello,I am using kubernetes alot,and also rook/ceph

I write python most of the time

and use kubernetes-python client to write some kind of operator myself,to maintain some cluster i can do works like ```docker commit```，by the pattern of ```docker in docker```

then I found the project,kopf.

Golang is the main language in deveploping operator,and I used rook/ceph and prometheus,they are useful

So I wonder if there is any real world operator is use kopf,so I can read its code,and learn to develop my own operator?

In fact,I found The Zalando Incubator itself use golang to deveplop es operator: https://github.com/zalando-incubator/es-operator

Why not use kopf？

**Comment by eshepelyuk** [comment]
@tarjintor there's a dedicated pinned issue for the feedbacks , may be you could find smth helpful there.
https://github.com/zalando-incubator/kopf/issues/100

**Comment by tarjintor** [comment]
ok,I will read it, thank you

**Comment by nolar** [comment]
Yes, the issue #100 has some mentions. Also, GitHub's dependency insights can be helpful: https://github.com/zalando-incubator/kopf/network/dependents
