### ISSUE TITLE
Freeze for 2+ operators of the same priority

### ISSUE THREAD

**Issue by nolar** [zalando-incubator/kopf#51]
## Current Behaviour

When 2+ operators with the same priority run (e.g. default of 0), both are working. Which breaks the purpose of the peering to prevent duplicated side-effects.

## Expected Behaviour

When 2+ operators with the same priority run, with peering configured and functional, only one should be functioning, others should freeze.

The best case would be that all operators issue a warning and freeze, so that the cluster becomes not served anymore — this will bring people attention sooner than if they negotiate which one should work. 2+ operators with the same priority is obviously a deployment error.

_Note: If the operators make a decision on which one runs, which one freezes (e.g. by the most recent pod start time, or by id, or anything else comparable), then it could happen that the old deployment in another namespace serves the cluster, when a new operator is expected to work. It is better to stop serving and bring people attention to resolve the situation._

## Suggestion

See [the module where it all happens](https://github.com/zalando-incubator/kopf/blob/d1cb7331b42255f1610e57e3855db203736bcacc/kopf/reactor/peering.py#L206-L215).

## Checklist

* [ ] Implementation.
* [ ] Tests — manually (there is no auto-tests for peering yet).
* [ ] Documentation (in `docs/peering.rst`)

**Comment by smileisak** [comment]
@nolar is this issue is already treated ?

**Comment by nolar** [comment]
@smileisak To my knowledge, no, it is free and waiting.
